NumPy - это open-source модуль для python, который предоставляет общие математические и числовые операции

# Подключение

In [4]:
#традиционный вариант подключения
import numpy as np

# Особые константы

Numpy реализует несколько особых значнений через константы. Например:

In [5]:
np.NaN
# not a number - Не число

nan

In [6]:
np.Inf
# infinity - бесконечно 

inf

# Массивы

Основной элемент в Numpy - это массив. \
\
Массивы из библиотеки Numpy работают быстрее в 10-100 раз чем наши любимые питоновские списки (list).  \
\
А еще они сильно меньше потребляют оперативной памяти. Это важно, когда вы работаете с реальными проектами.

In [12]:
lst = list(range(1_000_000))
len(lst)

%time for _ in range(10): lst2 = [x ** 2 for x in lst]

Wall time: 2.15 s


In [13]:
arr = np.arange(1_000_000)

%time for _ in range(10): arr2 = arr ** 2

Wall time: 19 ms


## Создание массива:

Самый простой способ создать Numpy массив с помощью функции array. \
\
При этом всем элементы в array должны быть одного типа, что отличает его от классического списка (list) Python.

In [9]:
a = np.array([1, 2, 3, 4], float)

print('Массив:', a)
print('Тип: ',type(a))
# обратное преобразование
print('Обратное преобразование: ', a.tolist())

Массив: [1. 2. 3. 4.]
Тип:  <class 'numpy.ndarray'>
Обратное преобразование:  [1.0, 2.0, 3.0, 4.0]


In [10]:
# показыаем, что можно также работать с np.array, как и с обычным list

print('1: ', a[0])
print('2: ', a[1:3])
print('3: ', a[-1])
a[0] = 5
print('4: ', a[0])

1:  1.0
2:  [2. 3.]
3:  4.0
4:  5.0


In [14]:
lst = [1, 2, 3, 4, 5]
arr1 = np.array(lst)
arr1

array([1, 2, 3, 4, 5])

array([[1, 2, 3],
       [4, 5, 6]])

## Многомерные массивы

Большая ценность numpy в том, что можно работать и многомерными массивами. Например, любое изображение - как минимум двумерный массив.

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]], int)
print('0: ', a)
print('1: ', a[0,0])
print('2: ', a[1,0])
print('3: ', a[0,1])

0:  [[1 2 3]
 [4 5 6]]
1:  1
2:  4
3:  2


In [17]:
# срезы (сленг - слайсы) с двмерным массивом
print('4: ', a[1,:])
print('5: ', a[:,2])
print('6: ', a[-1:, -2:])

4:  [4 5 6]
5:  [3 6]
6:  [[5 6]]


In [18]:
lst2 = [[1,2,3],[4,5,6]]
arr2 = np.array(lst2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## Как измерить длину списка?


Для списка используется *len* (выводит подмассивы), для массива(С вложенными штуками) используем *shape*, оно выдает количество массивов и количество подмассивов.

In [20]:
len(lst)

5

In [21]:
len(arr2[0])+len(arr2[1])

6

## Характеристики объектов numpy

In [24]:
# shape - выводит количество массивов и подмассивов.
a.shape

(2, 3)

In [23]:
# тип данных внутри
# напоминаем, массив numpy может хранить только один тип данных
a.dtype

dtype('int32')

In [25]:
# ndim - показывает какое у нас пространство, видно что двухмерное, так как массив двухмерный
a.ndim

2

1) Когда вы создаете массив, Numpy пытается понять из каких элементов вы пытаетесь его создать и подбирает наиболее подходящий тип данных.

2) Свойство dtype подскажет, какой тип данных у каждого элемента вашего массива.

## Действия с массивами

In [31]:
# изменения массива, поменять строки со столбцами
a.reshape(3,2)
# в процессе изменения размера создан новый массив, а не изменён старый

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# с помощью этой команды можно вытянуть массив в одномерную "строку"
a.flatten()

array([1, 2, 3, 4, 5, 6])

## Создание по-разному заполненных массивов

In [32]:
# аналог range для массивов
print(np.arange(5))
print(np.arange(1, 6, 2))

[0 1 2 3 4]
[1 3 5]


In [33]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
# k - номер диагонали, заполненный единицами
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [38]:
arr4 = np.full(5, -1)
arr4

array([-1, -1, -1, -1, -1])

In [39]:
# массив, который будет заполнен значениями от 0 до N
N=100
np.arange(N)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [87]:
arr1 = np.array([1.5, 2.5, 20], dtype =np.float64)
print(arr1)
# astype - меняет тип данных
arr2 = arr1.astype(np.int32)
print(arr2)

[ 1.5  2.5 20. ]
[ 1  2 20]


## Перебор элементов массива

In [45]:
a = np.array([1, 4, 5], int)
# простой перебор
for x in a:
    print(x)

1
4
5


In [43]:
# простой перебор для многомерного случая срабаотает плохо, он перебирает по первой размерности
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [44]:
# перебор правильным способом
for x in range(a.shape[0]):
    for y in range(a.shape[1]):
        print(a[x, y])

1.0
2.0
3.0
4.0
5.0
6.0


## Слайсинг

Для получения доступа к нескольким элементам указываем диапазон через двоеточие: \
\
*massiv[индекс_первого_элемента : индекс_последнего_элемента]*

In [46]:
arr = np.arange(10)
print(arr)
print(arr[2:9])
print(arr[1:2] + arr[-2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]
[ 9 10]


In [50]:
lst2 = [[3,2,3,4,5],[1,9,3,4,5],[1,2,3,8,5],[1,2,3,4,5],[1,2,3,4,10]]
m2d = np.array(lst2)
print(m2d)
print()
print(m2d[:6,0:1] + m2d[:6,3:4])
print()
print(m2d[1])

[[ 3  2  3  4  5]
 [ 1  9  3  4  5]
 [ 1  2  3  8  5]
 [ 1  2  3  4  5]
 [ 1  2  3  4 10]]

[[7]
 [5]
 [9]
 [5]
 [5]]

[1 9 3 4 5]


# Операции над массивами

## Математические операции над массивами

С массивами можно применять стандартные математические операции. Они будут работать так, как будето происходит поэлементая работа одной и той же операции. Для матричных операций есть специальные команды.

Стандартные математические операции применимы только к массивам одинаковых размеров.

In [52]:
a = np.arange(1, 4, 1, dtype=int)
b = np.arange(6, 9, 1, dtype=int)
print('a: ', a)
print('b: ', b)

a:  [1 2 3]
b:  [6 7 8]


In [53]:
a + b

array([ 7,  9, 11])

In [54]:
a - b

array([-5, -5, -5])

In [55]:
a * b

array([ 6, 14, 24])

In [56]:
a / b

array([0.16666667, 0.28571429, 0.375     ])

Кроме того, поэлементно могут быть применены другие математические операции

In [57]:
# корень
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [58]:
a = np.array([1.1, 1.5, 1.9], float)

In [59]:
# округление вниз
np.floor(a)

array([1., 1., 1.])

In [60]:
# округление вврех
np.ceil(a)

array([2., 2., 2.])

In [61]:
# округление по правилам математики
np.rint(a)

array([1., 2., 2.])

## Простые операции над массивами

### Для одномерных массивов

In [62]:
a = np.arange(1, 6, 1)
print(a)
print('Сумма: ', a.sum())
print('Перемножение: ', a.prod())

[1 2 3 4 5]
Сумма:  15
Перемножение:  120


In [63]:
# среднее (математическое ожидание)
a.mean()

3.0

In [64]:
# дисперсия (смещенная - это будет важно в дальнейшем)
a.var()

2.0

In [65]:
# стандартное отклонение (несмещенное - это тоже будет важно в дальнейшем)
a.std()

1.4142135623730951

In [66]:
a.min()

1

In [69]:
# индекс минимального элемента
a.argmin()

0

In [70]:
# clip позволяет "отрезать" значения сверху и снизу
a = np.array([6, 2, 5, -1, 0, 6, 2, 5, 4], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0., 5., 2., 5., 4.])

In [71]:
np.unique(a)

array([-1.,  0.,  2.,  4.,  5.,  6.])

### Для многомерных массивов

In [74]:
a = np.array([[5, 2], [4, 1], [3, -1]])
print(a)
print('Среднее по столбцам:', a.mean(axis=0))
print('Среднее по строкам:',a.mean(axis=1))

[[ 5  2]
 [ 4  1]
 [ 3 -1]]
Среднее по столбцам: [4.         0.66666667]
Среднее по строкам: [3.5 2.5 1. ]


## Логические операции над массивами

In [75]:
a = np.array([1, 3, 0])
b = np.array([0, 3, 2])

print(a > b, type(a>b))

[ True False False] <class 'numpy.ndarray'>


In [77]:
c = a > 2
print(c)

[False  True False]


In [78]:
# проверяем, что хотя бы один элемент истинен
print(any(c))
# проверяем, что все элементы истинны
print(all(c))

True
False


Если вы хотите провести сравнение логическим И или лолгическим ИЛИ, то необходимо воспользоваться специальнымыми методами:

In [81]:
np.logical_and(a > 0, a < 3)

array([ True, False, False])

С помощью *np.where* можно создать массив на основании условий. Синтаксис:

In [83]:
arr = np.where(a != 0, 1 / a, a)
print(arr)

[1.         0.33333333 0.        ]


C:\Users\B72A~1\AppData\Local\Temp/ipykernel_14552/392795139.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr = np.where(a != 0, 1 / a, a)


Можно проверять элементы массива на наличие NaN и бесконечностей.

In [84]:
a = np.array([1, np.NaN, np.Inf], float)

In [85]:
np.isnan(a)

array([False,  True, False])

In [86]:
np.isfinite(a)

array([ True, False, False])

## Выбор элементов массива по условию

Очень важной особенностью массивов является то, что элементы в них можно брать на основании других массивов. Это особенно полезно при реализации свёрточных нейронных сетей.

In [88]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [89]:
# а это результат фильтрации элементов
# обратите внимание, получился одномерный массив, содержащий только элементы, удовлетворяющие условию 
a[a >= 6]

array([6., 9.])

In [90]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

Обратите внимание, что если передать целочисленные значения, в качестве условий, то результат будет другой. Будут выбраные соответствующие элементы.

In [91]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([2., 2., 4., 8., 6., 4.])

In [92]:
# Для выбора значений из многомерных массивов необходимо передать массивы, которые определяют индексы по каждому из направлений. Они должны быть, естественно, целочисленными.
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

## Векторная и матричная математика с использованием numpy

Векторная математика в numpy - это главная причина того, что numpy стал ключевым модулем Python среди всех представленных модулей. Векторные вычисления позволяют значительно ускорить обработку численной информации.

### Скалярное произведение


Для двух векторов a и b одинаковой длины скалярное произведение считается по следующей формуле:

$ a*b = \sum_{i=0}^{len(a)}  a_i*b_i $

In [94]:
# скалярное произвдение векторов, также операция свёртки в свёрточных нейронных сетях 

a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

### Произведение матриц

Произведение матриц - это особая математическая операция, которая не эквивалентна произведени соответствующих элементов матриц. 

In [97]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)

In [96]:
np.dot(b, a)

array([ 6., 11.])

In [98]:
np.dot(a, b)

array([ 3., 13.])

### Определитель матриц

In [100]:
np.linalg.det(a)

-2.0